development:
  adapter: postgresql
  encoding: unicode
  database: webir_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: webir_testing
  pool: 5
  username:
  password:
